apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: sample-golang
build:
  cluster:
    pullSecretName: kaniko-secret
    #pullSecretPath: dockerconfig
    pullSecretMountPath: kaniko-secret
    namespace: tekton-pipelines
    dockerConfig:
      secretName: tekton-registry
  artifacts:
  - image: registry-harbor-registry.registry:5000/sample-golang
    kaniko:
      cache: {}
      insecure: true
      insecurePull: true
      cleanup: true


deploy:
  docker:
    images:
    - registry-harbor-registry.registry:5000/sample-golang

manifests:
  rawYaml:
  - k8s/**
