apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: sample-golang
build:
  cluster:
    namespace: default
  artifacts:
  - image: sample-golang
    platforms: ["linux/amd64"]
    kaniko:
      cache: {}

deploy:
  docker:
    images:
    - sample-golang

manifests:
  rawYaml:
  - k8s/**
