apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: sample-golang
build:
  cluster:
    namespace: default
  artifacts:
  - image: registry-harbor-registry.registry:5000/sample-golang
    kaniko:
      cache: {}
      insecure: true

deploy:
  docker:
    images:
    - registry-habor-registry.registry.svc.cluster.local:5000/sample-golang

manifests:
  rawYaml:
  - k8s/**
