apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: sample-golang
build:
  cluster:
    #pullSecretPath: /kaniko/.secret
    namespace: tekton-pipelines
    dockerConfig:
      path: /kaniko/.docker/config
  artifacts:
  - image: registry-harbor-registry.registry/sample-golang
    kaniko:
      dockerfile: ./.ertia/deploy/Dockerfile
      cache: {}
      insecure: true
      insecurePull: true
      #cleanup: true


deploy:
  docker:
    images:
    - registry-harbor-registry.registry/sample-golang

manifests:
  rawYaml:
  - k8s/**
