apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: sample-golang
build:
  artifacts:
  - image: sample-golang
    kaniko:
      cache: {}

deploy:
  docker:
    images:
    - sample-golang

manifests:
  rawYaml:
  - k8s-*
